# Generated by Django 5.1.1 on 2024-09-05 05:55

import django.db.models.deletion
import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.IntegerField()),
                ('remark', models.CharField(default='', max_length=128)),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_no', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('designation', models.CharField(max_length=64)),
                ('posting_place', models.CharField(max_length=64)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=64)),
                ('remark', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=employees.models.rename_image)),
                ('trash', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.department')),
            ],
        ),
    ]
