# Generated by Django 5.1.1 on 2024-09-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=128)),
                ('from_date', models.DateField()),
                ('days', models.IntegerField()),
                ('remark', models.CharField(default='', max_length=128)),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
    ]
